[tasks.run]
command = "cargo"
args = ["run"]

[tasks.run-r]
command = "cargo"
args = ["run", "--release"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]